import { FreshContext } from "$fresh/server.ts";
import { logger } from "~/src/logFile.ts";

// Jokes courtesy of https://punsandoneliners.com/randomness/programmer-jokes/
const JOKES = [
	"Why do programmers prefer dark mode? Because the light attracts bugs!",
	"How many programmers does it take to change a light bulb? None. That's a hardware issue.",
	"Why did the developer go broke? Because he used up all his cache.",
	"Why do Java developers wear glasses? Because they can't C#.",
	"What’s a programmer’s favorite hangout place? The Foo Bar.",
	"Why don't programmers like nature? It has too many bugs.",
	"What do you call a programmer from Finland? Nerdic.",
	"Why did the function break up with the variable? It had too many issues to resolve.",
	"How does a programmer fix a broken light bulb? By turning it off and on again.",
	"Why do Python developers prefer using snakes for their pets? They already have the best tuple.",
	"What did the JavaScript developer say when his code didn’t work? 'You must be async.'",
	"Why do C++ programmers make bad comedians? They never manage to throw exceptions.",
	"What do you call a developer who loves to fix bugs? A debugger.",
	"Why was the JavaScript developer sad? Because he didn't get the callback.",
	"Why was the computer cold? It left its Windows open.",
	"Why did the developer get a job at the bakery? Because he was good at dough (data).",
	"How do programmers say goodbye? 'Cya later, alligator, after a while, compiler.'",
	"Why are programming languages like dating? Because they all have their pros and cons, but you keep coming back to the one you’re most comfortable with.",
	"What do you call a group of 8 hobbits? A byte.",
	"Why did the Python programmer break up with his girlfriend? Because she couldn’t handle his recursion.",
	"What’s the object-oriented way to become wealthy? Inheritance.",
	"Why did the SQL database break up with the NoSQL database? It found someone with better relationships.",
	"Why did the programmer quit his job? He didn’t get arrays.",
	"Why do JavaScript developers prefer coffee? Because it’s Java.",
	"Why did the programmer go to the beach? Because he wanted to surf the web.",
	"What did the HTML tag say to the CSS? 'You style my world.'",
	"Why don’t programmers like working with numbers? They always have too many digits.",
	"Why was the JavaScript developer nervous? Because he was in a Promise relationship.",
	"What’s a programmer’s favorite type of music? Algo-rhythm.",
	"What did the class say to the object? 'You complete me.'",
	"Why did the programmer use the `return` statement? Because he wanted to return to his roots.",
	"Why was the function afraid of recursion? It was a stack overflow.",
	"What did the developer name his dog? Java.",
	"Why did the developer refuse to play hide and seek? Because good luck hiding from bugs.",
	"What do you call an optimistic programmer? A developer who believes his code is bug-free.",
	"Why did the function break up with the array? It just couldn't find its elements.",
	"Why do web developers always seem to be at the gym? They’re always working on their flexbox.",
	"Why did the Python script run away from home? Because it didn’t want to be imported anymore.",
	"Why do Java developers use beans? Because they’re better than just talking.",
	"Why do coders prefer dark coffee? Because they can't handle the light.",
	"Why did the array fail math class? Because it couldn’t find its value.",
	"How many engineers does it take to screw in a light bulb? None, they just redefine the concept of 'light'.",
	"Why did the developer go to therapy? Because he had too many unresolved issues.",
	"Why was the function so good at parties? It always knew how to return to the main event.",
	"What do you call a Python module that's always getting into trouble? A snake in the code.",
	"What’s the best way to make a decision in programming? Flip a coin and call it a 'Boolean' decision.",
	"Why was the website so bad at making decisions? It kept redirecting everything.",
	"Why do developers hate elevators? They don’t have enough control flow.",
	"Why did the computer go to the doctor? It had a virus.",
	"Why do developers love open source? Because it’s the best way to get bugs for free.",
	"Why don’t JavaScript developers use the elevator? They prefer callbacks.",
	"Why do web developers love autumn? Because of all the changes in leaves.",
	"What’s the difference between a developer and a musician? One plays with code, the other plays with notes.",
	"Why did the function hate its job? It was always returning nothing.",
	"What do you call a developer who can’t make decisions? A NULL pointer.",
	"Why did the Python developer get caught in the rain? He didn’t have a try block.",
	"What did the coder say to the server? 'I’m your client.'",
	"Why was the coder always calm? Because he had plenty of patience (Promises).",
	"What do you get when you cross a joke with a bug? A pun-derful error.",
	"Why was the developer tired? Because he had too many threads running.",
	"What did the database say to the query? 'I’ve got your back, just join me!'",
	"Why did the programmer’s wife leave him? Because he had no class.",
	"Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
	"Why was the router so good at making friends? Because it always knew how to connect.",
	"What did the programmer do after getting a haircut? He updated his ‘repo’.",
	"Why did the developer leave his job? He was stuck in an infinite loop.",
	"Why don’t developers like nature? It has too many bugs.",
	"What’s the difference between a programmer and a marketer? One has a lot of bugs, and the other creates them.",
	"Why did the developer start gardening? Because he loved working with arrays.",
	"What’s a programmer’s favorite exercise? Crunching numbers.",
	"Why do Python programmers prefer snakes? They’re comfortable with long-tails.",
	"Why was the CSS code so good at relationships? Because it always aligned perfectly.",
	"Why do programmers prefer cats? Because they’re independent and don’t need constant updates.",
	"What do you call a programmer who likes to eat pasta? A spaghetti coder.",
	"What’s a developer’s favorite kind of coffee? Java.",
	"Why did the Python developer get frustrated with his car? Because it was always giving him exceptions.",
	"Why don’t programmers like Star Wars? Because they can’t handle the Force.",
	"Why did the web developer break up with the front end? Because it wasn’t responsive enough.",
	"Why don’t Java developers use float? Because they don’t trust anything without precision.",
	"What’s the most common phrase in programming? 'It works on my machine.'",
	"Why do programmers hate telling jokes? Because the punchline is always a null reference exception.",
	"Why did the developer stay calm during the emergency? Because they were well-versed in handling exceptions.",
	"What’s a developer’s favorite part of a beach? The array of sandcastles.",
	"Why was the developer so good at making decisions? Because he was always thinking in binary.",
	"What do you call an insecure developer? A pointer.",
	"What did the SQL server say to the client? 'I’m going to make you an offer you can’t refuse.'",
	"Why do programmers use version control? To keep track of their past mistakes.",
	"Why did the developer get kicked out of the party? He couldn’t stop talking about his stack.",
	"What’s a Java developer’s favorite type of relationship? One that’s strongly typed.",
	"What did the server say to the client after a good connection? 'That’s what I call a successful handshake.'",
	"Why do programmers love cats? Because they’re good at catching exceptions.",
	"Why do programmers love coffee? Because it helps them Java-script.",
	"Why did the developer sit at the computer for hours? Because he had too many commits to make.",
	"What’s the first thing a developer does when they wake up? They check if their code has been pushed.",
	"Why do programmers prefer using ‘&&’ instead of ‘&’? Because they like to keep things short-circuited.",
	"What did the developer say when his code finally compiled? 'It’s alive!'",
	"Why did the HTML element break up with the CSS? Because it felt boxed in.",
	"What’s the best way to make a decision in programming? Flip a coin and call it a Boolean decision.",
	"Why do Java developers use ‘beans’? Because they’re better than just talking.",
	"What do you call a developer who loves to fix bugs? A debugger.",
	"What do you call a function that’s always working? A constant.",
	"Why did the developer fall asleep? Because he was caught in an infinite loop.",
	"What’s a JavaScript developer’s favorite dish? JSON!",
	"Why do developers hate finding bugs? It’s a never-ending loop.",
	"What do you get when you cross a joke with a bug? A pun-derful error.",
	"Why did the JavaScript developer give up on his relationship? Because he didn’t get the callback.",
];

/**
 * Handles an incoming request and returns a random joke from the JOKES array.
 *
 * @param _req - The incoming request object.
 * @param _ctx - The context object provided by the Fresh framework.
 * @returns A Response object containing a random joke.
 */
export const handler = (_req: Request, _ctx: FreshContext): Response => {
	logger.info("--> /api/joke: GET");
	logger.silly("We got a jokster on our hands 🤡");

	const body = JOKES[Math.floor(Math.random() * JOKES.length)];
	return new Response(body);
};
