
name: CD to AWS

on:
  push:
    branches: ["main", "16-setup-cd"]


permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_KEY" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

      - name: Deploy to AWS EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -i ~/.ssh/ec2_key.pem $USER@$HOST './startup.sh >> startup.log'
          ssh -i ~/.ssh/ec2_key.pem $USER@$HOST 'sudo systemctl restart deno-app &&  systemctl status deno-app >> startup.log'
        shell: /usr/bin/bash -e {0}
